### PR TITLE
feat: add more q & a

### PR DESCRIPTION
**Pull request by etolbakov**
Hey @AkashRajpurohit 
could you please take a look at the new content portion?

I decided to use `alternativeAnswers` for question `#40`. The original question `'I am getting underpaid for what my role has evolved into?'` sounds similar, but let me know if you'd like to split them?
Also, questions #17` and `#46` could be grouped on the "micromanaging" subject.

---
Regards, Eugene

### CODE REVIEW

**Comment by AkashRajpurohit** [comment]
Looks great to me, thanks for adding this.

**Comment by etolbakov** [comment]
@AkashRajpurohit I've noticed the emojis in the commit messages, f.e.
"feat: 📝 add more q & a"
Is it a preferred style? or is it appended automatically based on semver prefix? 
If the former - happy to use them next time.

**Comment by AkashRajpurohit** [comment]
hey @etolbakov I am adding those emojis before squashing and merging the commits, also it's just a preferred style for emojis but for commit messages I am following the [conventional commits spec](https://www.conventionalcommits.org/en/v1.0.0/#specification).

**Comment by etolbakov** [comment]
Thanks, that makes sense!
I will consider it next time.

**Pull request merged**
